apiVersion: v2
name: kube9-operator
version: 1.0.10
appVersion: "1.0.10"
description: Kubernetes Operator for Kube9 Cluster Management
keywords:
  - kubernetes
  - vscode
  - operator
home: https://www.kube9.io
sources:
  - https://charts.kube9.io

