apiVersion: v2
name: kube9-operator
version: 1.0.7
appVersion: "1.0.7"
description: Kubernetes Operator for kube9 VS Code Extension
keywords:
  - kubernetes
  - vscode
  - operator
home: https://kube9.io
sources:
  - https://charts.kube9.io
kubeVersion: ">= 1.24.0-0"

