apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "kube9-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube9-operator.labels" . | nindent 4 }}
rules:
# Manage status ConfigMap
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "create", "update", "patch"]

